name: "feed621"

volumes:
  database-vol:

networks:
  database-net:
  backend-net:

services:
  postgres:
    image: postgres:12.19-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.database-vol:/var/lib/postgres/feed621
    ports:
      - "5432:5432"
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  migrations:
    build:
      context: services/database
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    networks:
      - database-net
