services:
  backend:
    build:
      context: services/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SERVICE_ADDR: "0.0.0.0:${BACKEND_PORT}"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      RUST_LOG: "warn"
      RUST_LOG_STYLE: "always"
    networks:
      - database-net
      - backend-net
