services:
  postgres:
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:8.8
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - database-net
  backend:
    build:
      context: services/backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - migrations
    environment:
      SERVICE_ADDR: "0.0.0.0:8080"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      RUST_LOG: "debug"
      RUST_LOG_STYLE: "always"
    volumes:
      - ./services/backend:/app
    networks:
      - database-net
      - backend-net
