[package]
name = "backend"
version = "1.0.0"
edition = "2021"

[dependencies]
confgen = { path="./confgen" }

dotenvy = "0.15.7"
axum = "0.7.5"
tokio = { version="1.38.0", features = ["macros", "rt-multi-thread"] }

async-trait = "0.1.80"
serde = { version="1.0.200", features=["derive"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "tls-rustls", "postgres"] }
