name: "feed621"

networks:
  database-net:
  backend-net:

services:
  postgres:
    image: postgres:12.19-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ../.database-vol:/var/lib/postgres/data
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  migrations:
    build: ../services/migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    networks:
      - database-net
  nginx:
    image: nginx:stable-alpine3.19-slim
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ../services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-net
    ports:
      - "8080:80"
