name: "feed621"

networks:
  database-net:
  backend-net:

services:
  postgres:
    image: postgres:12.19-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../.database-vol:/var/lib/postgres/data
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  migrations:
    build:
      context: ../services/migrations
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    networks:
      - database-net
  nginx:
    image: nginx:stable-alpine3.19-slim
    restart: unless-stopped
    volumes:
      - ../services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-net
    ports:
      - "${APP_PORT}:80"
